"""feat_solicitudes_y_limites

Revision ID: 10a75d208055
Revises: 6a8f9b1c2d3e
Create Date: 2026-08-20 19:01:52.770232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a75d208055'
down_revision: Union[str, Sequence[str], None] = '6a8f9b1c2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_inscripcion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('torneo_id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_inscripcion_equipo_id'), 'solicitudes_inscripcion', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_inscripcion_torneo_id'), 'solicitudes_inscripcion', ['torneo_id'], unique=False)
    op.add_column('torneos', sa.Column('max_equipos', sa.Integer(), nullable=True))
    op.add_column('torneos', sa.Column('fecha_cierre_inscripcion', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torneos', 'fecha_cierre_inscripcion')
    op.drop_column('torneos', 'max_equipos')
    op.drop_index(op.f('ix_solicitudes_inscripcion_torneo_id'), table_name='solicitudes_inscripcion')
    op.drop_index(op.f('ix_solicitudes_inscripcion_equipo_id'), table_name='solicitudes_inscripcion')
    op.drop_table('solicitudes_inscripcion')
    # ### end Alembic commands ###
