"""feat: sprint2 modelos orm y roles

Revision ID: 26a5c1e5ee5f
Revises: 0003
Create Date: 2026-08-05 11:50:30.341381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB  # <--- AGREGA ESTA LÍNEA


# revision identifiers, used by Alembic.
revision: str = '26a5c1e5ee5f'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_nombre'), 'equipos', ['nombre'], unique=False)
    op.create_table('municipios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('clave_inegi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_inegi')
    )
    op.create_index(op.f('ix_municipios_nombre'), 'municipios', ['nombre'], unique=False)
    op.create_table('sports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_nombre'), 'sports', ['nombre'], unique=False)
    op.create_table('canchas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('meta_data_schema', JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torneos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('organizer_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('torneo_id', sa.UUID(), nullable=True),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], )
    )
    op.create_table('partidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('torneo_id', sa.UUID(), nullable=True),
    sa.Column('equipo_local_id', sa.UUID(), nullable=True),
    sa.Column('equipo_visitante_id', sa.UUID(), nullable=True),
    sa.Column('cancha_id', sa.UUID(), nullable=True),
    sa.Column('match_manager_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['match_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partido_id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(), nullable=False),
    sa.Column('meta_data', JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- AGREGADO MANUALMENTE: Índice GIN para JSONB ---
    op.create_index('ix_match_events_meta_data_gin', 'match_events', ['meta_data'], postgresql_using='gin')


def downgrade() -> None:
    # --- AGREGADO MANUALMENTE: Eliminar índice GIN al revertir ---
    op.drop_index('ix_match_events_meta_data_gin', table_name='match_events', postgresql_using='gin')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_events')
    op.drop_table('partidos')
    op.drop_table('inscripciones')
    op.drop_table('torneos')
    op.drop_table('participantes')
    op.drop_table('event_types')
    op.drop_table('canchas')
    op.drop_index(op.f('ix_sports_nombre'), table_name='sports')
    op.drop_table('sports')
    op.drop_index(op.f('ix_municipios_nombre'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_equipos_nombre'), table_name='equipos')
    op.drop_table('equipos')
    # ### end Alembic commands ###