"""add_equipos_torneos_tables

Revision ID: 372c6b5c7545
Revises: 26a5c1e5ee5f
Create Date: 2026-08-06 18:12:29.409739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '372c6b5c7545'
down_revision: Union[str, Sequence[str], None] = '26a5c1e5ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canchas', sa.Column('propietario_id', sa.UUID(), nullable=False))
    op.add_column('canchas', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('canchas', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'canchas', 'users', ['propietario_id'], ['id'])
    op.alter_column('event_types', 'meta_data_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_match_events_meta_data_gin'), table_name='match_events', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_match_events_meta_data_gin'), 'match_events', ['meta_data'], unique=False, postgresql_using='gin')
    op.alter_column('event_types', 'meta_data_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'canchas', type_='foreignkey')
    op.drop_column('canchas', 'updated_at')
    op.drop_column('canchas', 'created_at')
    op.drop_column('canchas', 'propietario_id')
    # ### end Alembic commands ###
