"""add_missing_datos_adicionales

Revision ID: 37e237e183fe
Revises: 372c6b5c7545
Create Date: 2026-08-16 21:01:55.773929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e237e183fe'
down_revision: Union[str, Sequence[str], None] = '372c6b5c7545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    op.alter_column('inscripciones', 'torneo_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inscripciones', 'equipo_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('participantes', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    op.add_column('partidos', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    op.add_column('sports', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    op.add_column('torneos', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'datos_adicionales')
    op.drop_column('torneos', 'datos_adicionales')
    op.drop_column('sports', 'datos_adicionales')
    op.drop_column('partidos', 'datos_adicionales')
    op.drop_column('participantes', 'datos_adicionales')
    op.alter_column('inscripciones', 'equipo_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inscripciones', 'torneo_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('equipos', 'datos_adicionales')
    # ### end Alembic commands ###
